general:
  debug: true
  cron: '*/15 * * * *'
darksky:
  key: DARKSKY_KEY
  units: auto
  language: en
  longitude: 76.851248
  latitude: 43.232025
influxdb:
  host: 134.209.240.215
  database: weather_almaty
  username:
password:
