general:
  debug: true
  cron: '*/15 * * * *'
darksky:
  key: 289134ea2b44f9c3c5f23e8c6de094d0
  units: auto
  language: en
  longitude: 76.851248
  latitude: 43.232025
influxdb:
  host: 134.209.240.215
  database: weather_almaty
  username: admin
password: admin
